### ISSUE TITLE
Image size

### ISSUE THREAD

**Issue by Schlump** [mapbender/docker#3]
Building this image (using PHP7) creates a ~ 2.7gb image ... mostly because of installing stuff like gdal and npm.
Is that really necessary ?

**Comment by AxxL** [comment]
Nah, that's not necessary. We will update this Docker image, it's a bit outdated and doesn't represent our current state.

**Comment by AxxL** [comment]
For the impatient, take a look here: https://github.com/yagajs/docker-mapbender3
We'll try to give @atd-schubert  a new Emacs-cup so that we can provide the code into this rep.

**Comment by Schlump** [comment]
Yeha well thanks for that link ;) I've built my own one using Based on  Nginx  image (Debian:Stretch) with PHP7

Image size of 373MB... gonna switch to Alpine though
